
package com.mycompany.business.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FTService", targetNamespace = "http://service.business.dtbafrica.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FTService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.dtbafrica.business.service.FtResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postTransaction", targetNamespace = "http://service.business.dtbafrica.com/", className = "com.dtbafrica.business.service.PostTransaction")
    @ResponseWrapper(localName = "postTransactionResponse", targetNamespace = "http://service.business.dtbafrica.com/", className = "com.dtbafrica.business.service.PostTransactionResponse")
    public FtResponse postTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        FTRequest arg0);

}
