
package com.mycompany.business.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FTServiceService", targetNamespace = "http://service.business.dtbafrica.com/", wsdlLocation = "http://192.168.23.132:8181/cxf/FTBusinessService?WSDL")
public class FTServiceService
    extends Service
{

    private final static URL FTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FTSERVICESERVICE_EXCEPTION;
    private final static QName FTSERVICESERVICE_QNAME = new QName("http://service.business.dtbafrica.com/", "FTServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.23.132:8181/cxf/FTBusinessService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FTSERVICESERVICE_WSDL_LOCATION = url;
        FTSERVICESERVICE_EXCEPTION = e;
    }

    public FTServiceService() {
        super(__getWsdlLocation(), FTSERVICESERVICE_QNAME);
    }

    public FTServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FTSERVICESERVICE_QNAME, features);
    }

    public FTServiceService(URL wsdlLocation) {
        super(wsdlLocation, FTSERVICESERVICE_QNAME);
    }

    public FTServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FTSERVICESERVICE_QNAME, features);
    }

    public FTServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FTServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FTService
     */
    @WebEndpoint(name = "FTServicePort")
    public FTService getFTServicePort() {
        return super.getPort(new QName("http://service.business.dtbafrica.com/", "FTServicePort"), FTService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FTService
     */
    @WebEndpoint(name = "FTServicePort")
    public FTService getFTServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.business.dtbafrica.com/", "FTServicePort"), FTService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FTSERVICESERVICE_EXCEPTION!= null) {
            throw FTSERVICESERVICE_EXCEPTION;
        }
        return FTSERVICESERVICE_WSDL_LOCATION;
    }

}
