/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 03 14:23:16 IST 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist LinkState
 */
public enum LinkStateEnum {

    // Duplicate
    DUPLICATE("Duplicate"),
    // Ignored
    IGNORED("Ignored"),
    // Linked
    LINKED("Linked"),
    // Orphaned
    ORPHANED("Orphaned");

    final String value;

    private LinkStateEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static LinkStateEnum fromValue(String value) {
        for (LinkStateEnum e : LinkStateEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
