package https.www_company_net;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-02-10T14:19:57.738+05:30
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "https://www.peoplestreme.net/", name = "PS_WSAccessSoap")
@XmlSeeAlso({https.www_company.ObjectFactory.class})
public interface PSWSAccessSoap {

    @WebResult(name = "GetXMLResultResult", targetNamespace = "https://www.peoplestreme.net/")
    @RequestWrapper(localName = "GetXMLResult", targetNamespace = "https://www.peoplestreme.net/", className = "https.www_peoplestreme.GetXMLResult")
    @WebMethod(operationName = "GetXMLResult", action = "https://www.peoplestreme.net/GetXMLResult")
    @ResponseWrapper(localName = "GetXMLResultResponse", targetNamespace = "https://www.peoplestreme.net/", className = "https.www_peoplestreme.GetXMLResultResponse")
    public https.www_company.GetXMLResultResponse.GetXMLResultResult getXMLResult(
        @WebParam(name = "sqltoken", targetNamespace = "https://www.peoplestreme.net/")
        java.lang.String sqltoken,
        @WebParam(name = "sqlquery", targetNamespace = "https://www.peoplestreme.net/")
        java.lang.String sqlquery
    );

    @WebResult(name = "GetSecurityTokenResult", targetNamespace = "https://www.peoplestreme.net/")
    @RequestWrapper(localName = "GetSecurityToken", targetNamespace = "https://www.peoplestreme.net/", className = "https.www_peoplestreme.GetSecurityToken")
    @WebMethod(operationName = "GetSecurityToken", action = "https://www.peoplestreme.net/GetSecurityToken")
    @ResponseWrapper(localName = "GetSecurityTokenResponse", targetNamespace = "https://www.peoplestreme.net/", className = "https.www_peoplestreme.GetSecurityTokenResponse")
    public https.www_company.GetSecurityTokenResponse.GetSecurityTokenResult getSecurityToken(
        @WebParam(name = "userid", targetNamespace = "https://www.peoplestreme.net/")
        java.lang.String userid,
        @WebParam(name = "password", targetNamespace = "https://www.peoplestreme.net/")
        java.lang.String password
    );
}
