package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-27T15:53:44.854+05:30
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "EnrollmentService", 
                  wsdlLocation = "file:/C:/Users/satish-s/workspace/SoapConsumeTest/src/main/resources/wsdl/HITS/HITS.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class EnrollmentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "EnrollmentService");
    public final static QName BasicHttpBindingIEnrollmentService = new QName("http://tempuri.org/", "BasicHttpBinding_IEnrollmentService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/satish-s/workspace/SoapConsumeTest/src/main/resources/wsdl/HITS/HITS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EnrollmentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/satish-s/workspace/SoapConsumeTest/src/main/resources/wsdl/HITS/HITS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EnrollmentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnrollmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnrollmentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EnrollmentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EnrollmentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EnrollmentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IEnrollmentService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEnrollmentService")
    public IEnrollmentService getBasicHttpBindingIEnrollmentService() {
        return super.getPort(BasicHttpBindingIEnrollmentService, IEnrollmentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEnrollmentService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEnrollmentService")
    public IEnrollmentService getBasicHttpBindingIEnrollmentService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEnrollmentService, IEnrollmentService.class, features);
    }

}
