package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-27T15:53:44.823+05:30
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IEnrollmentService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.integrationservice.ObjectFactory.class})
public interface IEnrollmentService {

    /**
     * <summary>
     *             Cancel equipment coverage
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="enrolledEquipment"></param>
     *             <param name="cancelReason" description="Cancel Reason">
     *             Reason that the equipment is being cancelled.
     *             Valid values: 1 = Customer cancelled, 2 = Non-payment, 3 = Claim limit reached, 4 = Coverage period ended, 5 = Fraud
     *             </param>
     *             <param name="cancelDate">
     *             <para>Date coverage was cancelled.</para>
     *             <para>Format: (UTC, <see href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601</see>) YYYY-MM-DD</para></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "CancelCoverage", action = "http://tempuri.org/IEnrollmentService/CancelCoverage")
    @Action(input = "http://tempuri.org/IEnrollmentService/CancelCoverage", output = "http://tempuri.org/IEnrollmentService/CancelCoverageResponse")
    @RequestWrapper(localName = "CancelCoverage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelCoverage")
    @ResponseWrapper(localName = "CancelCoverageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelCoverageResponse")
    @WebResult(name = "CancelCoverageResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result cancelCoverage(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber,
        @WebParam(name = "enrolledEquipment", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfEnrolledEquipment enrolledEquipment,
        @WebParam(name = "cancelReason", targetNamespace = "http://tempuri.org/")
        java.lang.Integer cancelReason,
        @WebParam(name = "cancelDate", targetNamespace = "http://tempuri.org/")
        java.lang.String cancelDate,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Return a list of active service plans
     *             </summary>
     *             <param name="clientId"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "SelectServicePlan", action = "http://tempuri.org/IEnrollmentService/SelectServicePlan")
    @Action(input = "http://tempuri.org/IEnrollmentService/SelectServicePlan", output = "http://tempuri.org/IEnrollmentService/SelectServicePlanResponse")
    @RequestWrapper(localName = "SelectServicePlan", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectServicePlan")
    @ResponseWrapper(localName = "SelectServicePlanResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectServicePlanResponse")
    @WebResult(name = "SelectServicePlanResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.ServicePlanResult selectServicePlan(
        @WebParam(name = "clientId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer clientId
    );

    /**
     * <summary>
     *             Return Service Plan Details and SKU mapping information
     *             </summary>
     *             <param name="clientId">The indentifier of the client.  <para>This will be provided by eSecuritel.</para></param>
     *             <param name="phoneFlag">Condition of phone.</param>
     *             <param name="featureCode">The feature or set of features the subscriber has signed up for</param>
     *             <param name="productDescription">The description of the product.</param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "GetServicePlanDetailAndSku", action = "http://tempuri.org/IEnrollmentService/GetServicePlanDetailAndSku")
    @Action(input = "http://tempuri.org/IEnrollmentService/GetServicePlanDetailAndSku", output = "http://tempuri.org/IEnrollmentService/GetServicePlanDetailAndSkuResponse")
    @RequestWrapper(localName = "GetServicePlanDetailAndSku", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServicePlanDetailAndSku")
    @ResponseWrapper(localName = "GetServicePlanDetailAndSkuResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServicePlanDetailAndSkuResponse")
    @WebResult(name = "GetServicePlanDetailAndSkuResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.ServicePlanDetailResult getServicePlanDetailAndSku(
        @WebParam(name = "clientId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer clientId,
        @WebParam(name = "phoneFlag", targetNamespace = "http://tempuri.org/")
        java.lang.Integer phoneFlag,
        @WebParam(name = "featureCode", targetNamespace = "http://tempuri.org/")
        java.lang.String featureCode,
        @WebParam(name = "productDescription", targetNamespace = "http://tempuri.org/")
        java.lang.String productDescription
    );

    /**
     * <summary>
     *             Return a list of the error codes
     *             </summary>        
     *             <returns></returns>
     */
    @WebMethod(operationName = "SelectResultCodes", action = "http://tempuri.org/IEnrollmentService/SelectResultCodes")
    @Action(input = "http://tempuri.org/IEnrollmentService/SelectResultCodes", output = "http://tempuri.org/IEnrollmentService/SelectResultCodesResponse")
    @RequestWrapper(localName = "SelectResultCodes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectResultCodes")
    @ResponseWrapper(localName = "SelectResultCodesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectResultCodesResponse")
    @WebResult(name = "SelectResultCodesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.ArrayOfEnrollmentResultCode selectResultCodes();

    /**
     * <summary>
     *             Resume equipment coverage that was suspended
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="enrolledEquipment"></param>
     *             <param name="resumeDate">
     *             <para>Date customer was resumed.</para>
     *             <para>Format: (UTC, <see href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601</see>) YYYY-MM-DD</para></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "Resume", action = "http://tempuri.org/IEnrollmentService/Resume")
    @Action(input = "http://tempuri.org/IEnrollmentService/Resume", output = "http://tempuri.org/IEnrollmentService/ResumeResponse")
    @RequestWrapper(localName = "Resume", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Resume")
    @ResponseWrapper(localName = "ResumeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResumeResponse")
    @WebResult(name = "ResumeResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result resume(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber,
        @WebParam(name = "enrolledEquipment", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfEnrolledEquipment enrolledEquipment,
        @WebParam(name = "resumeDate", targetNamespace = "http://tempuri.org/")
        java.lang.String resumeDate,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Change service plan for equipment
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="servicePlanChange"></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "ChangeServicePlan", action = "http://tempuri.org/IEnrollmentService/ChangeServicePlan")
    @Action(input = "http://tempuri.org/IEnrollmentService/ChangeServicePlan", output = "http://tempuri.org/IEnrollmentService/ChangeServicePlanResponse")
    @RequestWrapper(localName = "ChangeServicePlan", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeServicePlan")
    @ResponseWrapper(localName = "ChangeServicePlanResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeServicePlanResponse")
    @WebResult(name = "ChangeServicePlanResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result changeServicePlan(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber,
        @WebParam(name = "servicePlanChange", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfServicePlanChange servicePlanChange,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Change account number of all customers
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="newAccountNumber"></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "ChangeAccountNumber", action = "http://tempuri.org/IEnrollmentService/ChangeAccountNumber")
    @Action(input = "http://tempuri.org/IEnrollmentService/ChangeAccountNumber", output = "http://tempuri.org/IEnrollmentService/ChangeAccountNumberResponse")
    @RequestWrapper(localName = "ChangeAccountNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeAccountNumber")
    @ResponseWrapper(localName = "ChangeAccountNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeAccountNumberResponse")
    @WebResult(name = "ChangeAccountNumberResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result changeAccountNumber(
        @WebParam(name = "accountNumberChange", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.AccountNumberChange accountNumberChange,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    @WebMethod(operationName = "Enroll", action = "http://tempuri.org/IEnrollmentService/Enroll")
    @Action(input = "http://tempuri.org/IEnrollmentService/Enroll", output = "http://tempuri.org/IEnrollmentService/EnrollResponse")
    @RequestWrapper(localName = "Enroll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Enroll")
    @ResponseWrapper(localName = "EnrollResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnrollResponse")
    @WebResult(name = "EnrollResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result enroll(
        @WebParam(name = "customer", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.Customer customer,
        @WebParam(name = "equipment", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfEquipment equipment,
        @WebParam(name = "payment", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfPayment payment,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Change covered equipment
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="equipmentChange"></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "ChangeEquipment", action = "http://tempuri.org/IEnrollmentService/ChangeEquipment")
    @Action(input = "http://tempuri.org/IEnrollmentService/ChangeEquipment", output = "http://tempuri.org/IEnrollmentService/ChangeEquipmentResponse")
    @RequestWrapper(localName = "ChangeEquipment", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeEquipment")
    @ResponseWrapper(localName = "ChangeEquipmentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeEquipmentResponse")
    @WebResult(name = "ChangeEquipmentResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result changeEquipment(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber,
        @WebParam(name = "equipmentChange", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfEquipmentChange equipmentChange,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Change the phone number of equipment
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="phoneNumberChange"></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "ChangePhoneNumber", action = "http://tempuri.org/IEnrollmentService/ChangePhoneNumber")
    @Action(input = "http://tempuri.org/IEnrollmentService/ChangePhoneNumber", output = "http://tempuri.org/IEnrollmentService/ChangePhoneNumberResponse")
    @RequestWrapper(localName = "ChangePhoneNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangePhoneNumber")
    @ResponseWrapper(localName = "ChangePhoneNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangePhoneNumberResponse")
    @WebResult(name = "ChangePhoneNumberResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result changePhoneNumber(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber,
        @WebParam(name = "phoneNumberChange", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfPhoneNumberChange phoneNumberChange,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Return a list of active models.
     *             </summary>
     *             <param name="clientId"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "SelectSku", action = "http://tempuri.org/IEnrollmentService/SelectSku")
    @Action(input = "http://tempuri.org/IEnrollmentService/SelectSku", output = "http://tempuri.org/IEnrollmentService/SelectSkuResponse")
    @RequestWrapper(localName = "SelectSku", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectSku")
    @ResponseWrapper(localName = "SelectSkuResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectSkuResponse")
    @WebResult(name = "SelectSkuResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.ModelResult selectSku(
        @WebParam(name = "clientId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer clientId
    );

    /**
     * <summary>
     *             Return Service Plan Details 
     *             </summary>
     *             <param name="clientId">The indentifier of the client.  <para>This will be provided by eSecuritel.</para></param>
     *             <param name="servicePlanId">The identifier of the service plan</param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "GetServicePlanDetails", action = "http://tempuri.org/IEnrollmentService/GetServicePlanDetails")
    @Action(input = "http://tempuri.org/IEnrollmentService/GetServicePlanDetails", output = "http://tempuri.org/IEnrollmentService/GetServicePlanDetailsResponse")
    @RequestWrapper(localName = "GetServicePlanDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServicePlanDetails")
    @ResponseWrapper(localName = "GetServicePlanDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServicePlanDetailsResponse")
    @WebResult(name = "GetServicePlanDetailsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.ServicePlanDetailResult getServicePlanDetails(
        @WebParam(name = "clientId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer clientId,
        @WebParam(name = "servicePlanId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer servicePlanId
    );

    /**
     * <summary>
     *             Suspend equipment coverage
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="enrolledEquipment"></param>
     *             <param name="suspendReason">
     *             <para>Reason equipment is being suspended</para>
     *              <para>Valid values: 1 = Customer cancelled, 2 = Non-payment, 3 = Claim limit reached, 4 = Coverage period ended, 5 = Fraud</para>
     *             </param>
     *             <param name="suspendDate">
     *             <para>Date customer was suspended.</para>
     *             <para>Format: (UTC, <see href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601</see>) YYYY-MM-DD</para></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "Suspend", action = "http://tempuri.org/IEnrollmentService/Suspend")
    @Action(input = "http://tempuri.org/IEnrollmentService/Suspend", output = "http://tempuri.org/IEnrollmentService/SuspendResponse")
    @RequestWrapper(localName = "Suspend", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Suspend")
    @ResponseWrapper(localName = "SuspendResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SuspendResponse")
    @WebResult(name = "SuspendResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result suspend(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber,
        @WebParam(name = "enrolledEquipment", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfEnrolledEquipment enrolledEquipment,
        @WebParam(name = "suspendReason", targetNamespace = "http://tempuri.org/")
        java.lang.Integer suspendReason,
        @WebParam(name = "suspendDate", targetNamespace = "http://tempuri.org/")
        java.lang.String suspendDate,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Modify customer information
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="customerChange"></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "ChangeCustomerInformation", action = "http://tempuri.org/IEnrollmentService/ChangeCustomerInformation")
    @Action(input = "http://tempuri.org/IEnrollmentService/ChangeCustomerInformation", output = "http://tempuri.org/IEnrollmentService/ChangeCustomerInformationResponse")
    @RequestWrapper(localName = "ChangeCustomerInformation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeCustomerInformation")
    @ResponseWrapper(localName = "ChangeCustomerInformationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeCustomerInformationResponse")
    @WebResult(name = "ChangeCustomerInformationResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result changeCustomerInformation(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber,
        @WebParam(name = "customerChange", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfCustomerChange customerChange,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Transfer equipment coverage to a different account number
     *             </summary>
     *             <param name="accountNumber"></param>
     *             <param name="newAccountNumber"></param>
     *             <param name="equipmentChange"></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "TransferEquipment", action = "http://tempuri.org/IEnrollmentService/TransferEquipment")
    @Action(input = "http://tempuri.org/IEnrollmentService/TransferEquipment", output = "http://tempuri.org/IEnrollmentService/TransferEquipmentResponse")
    @RequestWrapper(localName = "TransferEquipment", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferEquipment")
    @ResponseWrapper(localName = "TransferEquipmentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferEquipmentResponse")
    @WebResult(name = "TransferEquipmentResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result transferEquipment(
        @WebParam(name = "accountNumberChange", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.AccountNumberChange accountNumberChange,
        @WebParam(name = "newCustomer", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.Customer newCustomer,
        @WebParam(name = "equipmentChange", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfEquipmentChange equipmentChange,
        @WebParam(name = "payment", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfPayment payment,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    /**
     * <summary>
     *             Change account number of a customer
     *             </summary>
     *             <param name="newAccountNumber"></param>
     *             <param name="phoneNumer"></param>
     *             <param name="channelInformation"></param>
     *             <returns></returns>
     */
    @WebMethod(operationName = "ChangeCustomerAccountNumber", action = "http://tempuri.org/IEnrollmentService/ChangeCustomerAccountNumber")
    @Action(input = "http://tempuri.org/IEnrollmentService/ChangeCustomerAccountNumber", output = "http://tempuri.org/IEnrollmentService/ChangeCustomerAccountNumberResponse")
    @RequestWrapper(localName = "ChangeCustomerAccountNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeCustomerAccountNumber")
    @ResponseWrapper(localName = "ChangeCustomerAccountNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeCustomerAccountNumberResponse")
    @WebResult(name = "ChangeCustomerAccountNumberResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result changeCustomerAccountNumber(
        @WebParam(name = "newAccountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String newAccountNumber,
        @WebParam(name = "phoneNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String phoneNumber,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );

    @WebMethod(operationName = "UpdatePayment", action = "http://tempuri.org/IEnrollmentService/UpdatePayment")
    @Action(input = "http://tempuri.org/IEnrollmentService/UpdatePayment", output = "http://tempuri.org/IEnrollmentService/UpdatePaymentResponse")
    @RequestWrapper(localName = "UpdatePayment", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePayment")
    @ResponseWrapper(localName = "UpdatePaymentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePaymentResponse")
    @WebResult(name = "UpdatePaymentResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.integrationservice.Result updatePayment(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber,
        @WebParam(name = "payment", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ArrayOfPayment payment,
        @WebParam(name = "channelInformation", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.integrationservice.ChannelInformation channelInformation
    );
}
