package jaxb.marketplace.com.brightstar.marketplace.svcs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-02-08T12:28:13.466+05:30
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://svcs.marketplace.brightstar.com/", name = "OrderManagementServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderManagementServiceSoap {

    @WebResult(name = "CancelOrderResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.CancelOrder")
    @WebMethod(operationName = "CancelOrder", action = "http://svcs.marketplace.brightstar.com/CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.CancelOrderResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderResponse cancelOrder(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderRequest request
    );

    @WebResult(name = "GetShipmentRateResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "GetShipmentRate", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.GetShipmentRate")
    @WebMethod(operationName = "GetShipmentRate", action = "http://svcs.marketplace.brightstar.com/GetShipmentRate")
    @ResponseWrapper(localName = "GetShipmentRateResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.GetShipmentRateResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPShipmentResponse getShipmentRate(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPShipmentRequest request
    );

    @WebResult(name = "GetOrdersBySearchParametersResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "GetOrdersBySearchParameters", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.GetOrdersBySearchParameters")
    @WebMethod(operationName = "GetOrdersBySearchParameters", action = "http://svcs.marketplace.brightstar.com/GetOrdersBySearchParameters")
    @ResponseWrapper(localName = "GetOrdersBySearchParametersResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.GetOrdersBySearchParametersResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderListResponse getOrdersBySearchParameters(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderSearchRequest request
    );

    @WebResult(name = "CreateAndConfirmOrderResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "CreateAndConfirmOrder", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.CreateAndConfirmOrder")
    @WebMethod(operationName = "CreateAndConfirmOrder", action = "http://svcs.marketplace.brightstar.com/CreateAndConfirmOrder")
    @ResponseWrapper(localName = "CreateAndConfirmOrderResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.CreateAndConfirmOrderResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderResponse createAndConfirmOrder(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderRequest request
    );

    @WebResult(name = "ModifyOrderResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "ModifyOrder", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.ModifyOrder")
    @WebMethod(operationName = "ModifyOrder", action = "http://svcs.marketplace.brightstar.com/ModifyOrder")
    @ResponseWrapper(localName = "ModifyOrderResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.ModifyOrderResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderResponse modifyOrder(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderRequest request
    );

    @WebResult(name = "ConfirmOrderResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "ConfirmOrder", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.ConfirmOrder")
    @WebMethod(operationName = "ConfirmOrder", action = "http://svcs.marketplace.brightstar.com/ConfirmOrder")
    @ResponseWrapper(localName = "ConfirmOrderResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.ConfirmOrderResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderResponse confirmOrder(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderRequest request
    );

    @WebResult(name = "GetEstimatedDatesResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "GetEstimatedDates", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.GetEstimatedDates")
    @WebMethod(operationName = "GetEstimatedDates", action = "http://svcs.marketplace.brightstar.com/GetEstimatedDates")
    @ResponseWrapper(localName = "GetEstimatedDatesResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "com.brightstar.marketplace.svcs.GetEstimatedDatesResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPDatesResponse getEstimatedDates(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPDatesRequest request
    );

    @WebResult(name = "GetSecurityTokenResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "GetSecurityToken", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "jaxb.marketplace.com.brightstar.marketplace.svcs.GetSecurityToken")
    @WebMethod(operationName = "GetSecurityToken", action = "http://svcs.marketplace.brightstar.com/GetSecurityToken")
    @ResponseWrapper(localName = "GetSecurityTokenResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "jaxb.marketplace.com.brightstar.marketplace.svcs.GetSecurityTokenResponse")
    public java.lang.String getSecurityToken(
        @WebParam(name = "userName", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        java.lang.String password
    );

    @WebResult(name = "CreateOrderResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "CreateOrder", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "jaxb.marketplace.com.brightstar.marketplace.svcs.CreateOrder")
    @WebMethod(operationName = "CreateOrder", action = "http://svcs.marketplace.brightstar.com/CreateOrder")
    @ResponseWrapper(localName = "CreateOrderResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "jaxb.marketplace.com.brightstar.marketplace.svcs.CreateOrderResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderResponse createOrder(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderRequest request
    );

    @WebResult(name = "GetOrderByOrderIDResult", targetNamespace = "http://svcs.marketplace.brightstar.com/")
    @RequestWrapper(localName = "GetOrderByOrderID", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "jaxb.marketplace.com.brightstar.marketplace.svcs.GetOrderByOrderID")
    @WebMethod(operationName = "GetOrderByOrderID", action = "http://svcs.marketplace.brightstar.com/GetOrderByOrderID")
    @ResponseWrapper(localName = "GetOrderByOrderIDResponse", targetNamespace = "http://svcs.marketplace.brightstar.com/", className = "jaxb.marketplace.com.brightstar.marketplace.svcs.GetOrderByOrderIDResponse")
    public jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderResponse getOrderByOrderID(
        @WebParam(name = "request", targetNamespace = "http://svcs.marketplace.brightstar.com/")
        jaxb.marketplace.com.brightstar.marketplace.svcs.MPOrderRequest request
    );
}
