
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.mycompany.cxf.soap.skeleton;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2015-08-15T22:44:36.996+05:30
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "PersonService",
                      portName = "PersonServicePort",
                      targetNamespace = "http://model.soap.cxf.mycompany.com/",
                      wsdlLocation = "file:/NotBackedUp/cpandey/Development/FUSE-WORKSPACES/OtherWorkSpace/TestWebService_CXF/PersonServicePort.wsdl",
                      endpointInterface = "com.mycompany.cxf.soap.skeleton.PersonService")
                      
public class PersonServiceImpl implements PersonService {

    private static final Logger LOG = Logger.getLogger(PersonServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mycompany.cxf.soap.skeleton.PersonService#getPerson(int  id )*
     */
    public com.mycompany.cxf.soap.skeleton.Person getPerson(int id) throws PersonException_Exception    { 
        LOG.info("Executing operation getPerson");
        System.out.println(id);
        try {
            com.mycompany.cxf.soap.skeleton.Person _return = new com.mycompany.cxf.soap.skeleton.Person();
            _return.setAge(-1785801165);
            _return.setId(11659877);
            _return.setName("Name117735225");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PersonException_Exception("PersonException...");
    }

    /* (non-Javadoc)
     * @see com.mycompany.cxf.soap.skeleton.PersonService#deletePerson(int  id )*
     */
    public com.mycompany.cxf.soap.skeleton.Person deletePerson(int id) throws PersonException_Exception    { 
        LOG.info("Executing operation deletePerson");
        System.out.println(id);
        try {
            com.mycompany.cxf.soap.skeleton.Person _return = new com.mycompany.cxf.soap.skeleton.Person();
            _return.setAge(1221386909);
            _return.setId(-1434475869);
            _return.setName("Name1845851249");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PersonException_Exception("PersonException...");
    }

    /* (non-Javadoc)
     * @see com.mycompany.cxf.soap.skeleton.PersonService#putPerson(com.mycompany.cxf.soap.skeleton.Person  arg0 )*
     */
    public com.mycompany.cxf.soap.skeleton.Person putPerson(com.mycompany.cxf.soap.skeleton.Person arg0) { 
        LOG.info("Executing operation putPerson");
        System.out.println(arg0);
        try {
            com.mycompany.cxf.soap.skeleton.Person _return = new com.mycompany.cxf.soap.skeleton.Person();
            _return.setAge(-1960932200);
            _return.setId(1713347273);
            _return.setName("Name-1576139689");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
